### ISSUE TITLE
downloading issues behind the firewall

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/lightsource2-recipes#1]
I'm having major issues with downloading sources from behind the firewall.  If I unset the `REQUESTS_CA_BUNDLE `environmental variable then I can download sources, but then I can't upload to our internal server.  It seems that I can either build or upload, but not both. Ugh.

**Comment by ericdill** [comment]
Note that the recipes I am having difficulty with are located in the 'needs work' folder

**Comment by danielballan** [comment]
New anaconda server resolved this issue.
