### ISSUE TITLE
Pandas 0.20.2

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/lightsource2-recipes#177]
Can I get pandas 0.20.2, this should fix a problem with pandas plot and matplotlib 2.0.2

**Comment by tacaswell** [comment]
we are not going to re-package pandas.

**Comment by CJ-Wright** [comment]
Can we update the conda-forge mirror then? Currently there is a 0.20.2 build on conda-forge but I can't seem to be able to install it inside the ring.
