### ISSUE TITLE
Fix dependencies of hklpy

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/lightsource2-recipes#182]
Based on reports, one or more of the following are probably missing from our recipe. I haven't checked.

gsl libiconv pcre hkl

**Comment by tacaswell** [comment]
Check the extra stuff added to CSX

**Comment by danielballan** [comment]
Noting here an in-person conversation with @tacaswell:

It's likely that our recipe for hkl (not hklpy) failed to properly list all its dependencies, and that this is the cause of the problem. Complicating matters, the hkl package cannot be built in our standard Docker because it needs particular system libs to be available. The binary that we distribute now was built manually by Tom on freyja. It will need to be manually rebuilt with a corrected recipe that properly declares all the dependencies.

**Comment by stuartcampbell** [comment]
Just to check, the `hkl` package is the same as the `libhkl` package in debian ?

**Comment by danielballan** [comment]
Sorry, neither @tacaswell or I know the answer to that.

**Comment by klauer** [comment]
The hkl package is the same - but I don't recall if we had local modifications https://packages.qa.debian.org/h/hkl.html

**Comment by mrakitin** [comment]
I think it's taken care of by https://github.com/NSLS-II/lightsource2-recipes/pull/303 and https://github.com/NSLS-II/lightsource2-recipes/pull/310.
