### ISSUE TITLE
Create a 28-ID-2 metapackage.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/lightsource2-recipes#237]
Once merged, add it to `extra_packages` in the `production` inventory in NSLS-II/playbooks.

**Comment by jrmlhermitte** [comment]
looks like #16 half closes this. will you take care of adding to production or should i go ahead? (ping me when PR if yes)

**Comment by danielballan** [comment]
Closed by #254 

See https://github.com/NSLS-II/playbooks/pull/20 for the corresponding up in the inventory.

**Comment by danielballan** [comment]
Ha! Jinx!

**Comment by jrmlhermitte** [comment]
oops edited from 16 -> 254 in PR ref

(i figured you may have been doing it why i asked :-D)
