### ISSUE TITLE
lmfit and scikit beam

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/lightsource2-recipes#331]
We should eventually remove the strict dep of scikit-beam on lmfit:
- find out why we have it exactly again
- update lmfit
- change this line here [here](https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/scikit-beam/meta.yaml#L33)

curently, xray larch requires `lmfit.lineshapes.moffat` which is only available in a later version of `lmfit`. So we now have an incompatibility between `scikit-beam` and `xraylarch`

**Comment by jrmlhermitte** [comment]
5 tests currently fail, related to xrf:
```
skbeam/core/fitting/tests/test_xrf_fit.py::test_fit FAILED                                                                                    [ 22%]
skbeam/core/fitting/tests/test_xrf_fit.py::test_define_range FAILED                                                                           [ 23%]
skbeam/core/fitting/tests/test_xrf_fit.py::test_pre_fit FAILED                                                                                [ 24%]
skbeam/core/fitting/tests/test_xrf_fit.py::test_escape_peak FAILED                                                                            [ 25%]
skbeam/core/fitting/tests/test_xrf_fit.py::test_pixel_fit_multiprocess FAILED                                                                 [ 26%] (edited
```

**Comment by mrakitin** [comment]
Just discussed it with @licode, this is used in PyXRF <-- scikit-beam <-- lmfit (old version). No new version was implemented.

**Comment by mrakitin** [comment]
This was resolved recently by @dmgav.
