### ISSUE TITLE
lmfit broken

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/lightsource2-recipes#37]
Got the following error @licode 
/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved t[67/1409]
gets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/cwright/other_src/analysis.py in <module>()
      5 import pyFAI
      6 import matplotlib.pyplot as plt
----> 7 from xpd_workflow.single_event_integration import single_mask_integration
      8 from tifffile import imsave
      9 from skbeam.io.save_powder_output import save_output

/home/cwright/dev/cwright/xpd_workflow/xpd_workflow/single_event_integration.py in <module>()
      9 
     10 #from sidewinder_spec.utils.handlers import *
---> 11 from skbeam.diffraction import bin_edges_to_centers
     12 from skbeam.io.save_powder_output import save_output
     13 from skbeam.core.utils import twotheta_to_q

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/skbeam/diffraction.py in <module>()
     41 
     42 # import fitting models
---> 43 from skbeam.core.fitting import Lorentzian2Model
     44 from skbeam.core.fitting import gaussian
     45 from skbeam.core.fitting import lorentzian

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/skbeam/core/fitting/__init__.py in <module>()
     41 logger = logging.getLogger(__name__)
     42 from .background import snip_method
---> 43 from .models import (Lorentzian2Model, ComptonModel, ElasticModel)
     44 
     45 from .lineshapes import (gaussian, lorentzian, lorentzian2, voigt, pvoigt,

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/skbeam/core/fitting/models.py in <module>()
     46 import logging
     47 
---> 48 from lmfit import Model
     49 from .lineshapes import (elastic, compton, lorentzian2)
     50 from .base.parameter_data import get_para

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/lmfit-0.8.3-py3.5.egg/lmfit/__init__.py in <module>()
     47 from .uncertainties import ufloat, correlated_values
     48 
---> 49 from .ui import Fitter
     50 
     51 ## versioneer code

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/lmfit-0.8.3-py3.5.egg/lmfit/ui/__init__.py in <module>()
     35 
     36 if has_ipython:
---> 37     from .ipy_fitter import NotebookFitter
     38     Fitter = NotebookFitter

/home/cwright/anaconda/envs/dp/lib/python3.5/site-packages/lmfit-0.8.3-py3.5.egg/lmfit/ui/ipy_fitter.py in <module>()
     21 else:
     22     # as of IPython 3.x
---> 23     from IPython.html.widgets import Dropdown
     24     from IPython.html.widgets import Button
     25     from IPython.html.widgets import Box

ImportError: No module named 'widgets'

**Comment by licode** [comment]
install ipywidgets, and try it again.

**Comment by CJ-Wright** [comment]
That did it.
