### ISSUE TITLE
Package pyCHX.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/lightsource2-recipes#374]
This will involve reviewing pyCHX's `requirements.txt`.

Quoting an email from @mrakitin:

> I thing we eventually need to get rid of git+https://… dependencies in requirements.txt:
git+https://github.com/scikit-beam/scikit-beam.git#egg=scikit-beam
git+https://github.com/NSLS-II-CHX/eiger-io.git#eiger-io
git+https://github.com/NSLS-II-CHX/chxtools.git#egg=chxtools
git+https://github.com/Nikea/xray-vision.git#Xray-vision
git+https://github.com/ChrisBeaumont/mpl-modest-image
 
> We do have a scikit-beam, eiger-io, chxtools, and xray-vision conda packages. The last one – mpl-modest-image – probably should be replaced with something else. As a quick solution for the coming users, we can definitely install the package from pip with those dependencies, but in long term I’d recommend to build a better approach in supplying the package to the users via a conda package. There are many advantages of this approach.

**Comment by danielballan** [comment]
I have pip-installed pyCHX from source (making manual simplifications to its `requirements.txt`) into analysis-2018-2.1 on xf11id-srv1 for now to take the time pressure off of this.

**Comment by mrakitin** [comment]
We now have the package maintained by @yugangzhang: https://anaconda.org/lightsource2-tag/pychx/files.
