### ISSUE TITLE
Bring together with conda-forge

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/lightsource2-recipes#391]
Is there any interest in bringing together with conda-forge?

**Comment by CJ-Wright** [comment]
Sorry I should have clarified (use conda-forge's recipes (and update conda-forges to use advancements made here) not use the conda-forge binaries directly).

**Comment by danielballan** [comment]
Yes, there is a plan to fork CF recipes rather than copy/paste them.

**Comment by mrakitin** [comment]
We are moving to https://github.com/nsls-ii-forge, which uses CF infrastructure. We will discuss later if we want to use the binaries produced by CF's feedstocks.
