### ISSUE TITLE
Import pyfftw from conda-forge

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/lightsource2-recipes#477]
https://github.com/conda-forge/pyfftw-feedstock

**Comment by mrakitin** [comment]
Built and pushed to https://anaconda.org/lightsource2-tag/pyfftw.

**Comment by mrakitin** [comment]
The built package failed to install into FXI's `collection-2018-3.2` env:
```
Solving environment: ...working... failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - libgcc-ng==7.2.0=hdf63c60_3
  - pyfftw -> libgcc-ng[version='>=7.3.0']
Use "conda info <package>" to see the dependencies for each package.non-zero return code
```
I'll have to have a look why it's conflicting and rework the recipe.

**Comment by mrakitin** [comment]
OK, 09279d0 resolved the issue. The package was pushed to the `collection-2018-3.2` and `analysis-2018-3.2` envs of FXI.

**Comment by licode** [comment]
thanks for quickly taking care of this, @mrakitin
