### ISSUE TITLE
Set up TravisCI integration and validate meta.yaml files

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#509]
[conda-verify](https://github.com/conda/conda-verify) can be used for that purpose.

**Comment by danielballan** [comment]
Good idea. Seems like an open question whether we should do this before or after reorganizing this from one "monorepo" into a constellation of repos, one per package, forked from conda-forge.

**Comment by mrakitin** [comment]
Closing for now.
