### ISSUE TITLE
Avoid shared memory bug in openmpi>=3.1.2

### ISSUE THREAD

**Issue by leofang** [NSLS-II/lightsource2-recipes#523]
Currently we build v3.1.2 in `nsls2-tag`:
https://github.com/NSLS-II/lightsource2-recipes/blob/87723db7b7d8c3b7475b1e478ac1a394326dec48/recipes-tag/openmpi/meta.yaml#L2
However, this version seems to be buggy. If one spawns a few MPI processes, let them do some work, but terminate them abnormally (`Ctrl-C` and whatnot), it can be seen that in `/dev/shm/` there will be shared memory segments related to openmpi's `vader` component (don't ask me what this is...) that are not unlinked by openmpi during the cleanup phase:
```bash
leofang@xf03id-srv5:~$ ls -lt /dev/shm | more
total 28464
-rw------- 1 leofang leofang 4194312 Jan 25 23:06 vader_segment.xf03id-srv5.73dc0001.2
-rw------- 1 leofang leofang 4194312 Jan 25 23:06 vader_segment.xf03id-srv5.73dc0001.3
-rw------- 1 leofang leofang 4194312 Jan 25 23:06 vader_segment.xf03id-srv5.73dc0001.1
-rw------- 1 leofang leofang 4194312 Jan 25 23:06 vader_segment.xf03id-srv5.73dc0001.0
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:08 vader_segment.xf03id-srv5.32270001.2
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:08 vader_segment.xf03id-srv5.32270001.0
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:08 vader_segment.xf03id-srv5.32270001.3
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:08 vader_segment.xf03id-srv5.32270001.1
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:07 vader_segment.xf03id-srv5.358e0001.3
-rw------- 1 xjhuang xjhuang 4194312 Jan 15 11:07 vader_segment.xf03id-srv5.358e0001.2
......
``` 
and they will remain there until the system is reboot, eating up slowly the system's memory! 

Based on openmpi's changelog (see [here](https://raw.githubusercontent.com/open-mpi/ompi/v3.1.x/NEWS)), it seems that `vader` was reworked in v3.1.2, presumably this bug sneaked in by then. ~~There's a bug fix in v3.1.3 hopefully would address this~~; if not, we can downgrade to v3.1.1, which I tested and worked without this issue. 

(**UPDATE**: v3.1.3 also has this problem, has to use 3.1.1...)

I have other questions related to building conda packages for `mpi4py`, `openmpi`, and `mpich`, but perhaps I should ask them somewhere else...

**Comment by tacaswell** [comment]
@leofang can you sync our recipe with the conda-forge one (which sadly for now is a copy-paste job :disappointed: )

**Comment by leofang** [comment]
Sure, happy to do. But let me first check with Open MPI people and see if this is a known bug or caused by other problems.

**Comment by leofang** [comment]
@tacaswell since you brought up, I'd also like to copy and paste the conda-forge recipes for `mpi4py` and `mpich`. This would solve the MPI nuisance. Is it OK?

**Comment by stuartcampbell** [comment]
@leofang Definately - go ahead

**Comment by leofang** [comment]
ref: open-mpi/ompi/issues/6322
