### ISSUE TITLE
rebuild packages generated from single recipes 

### ISSUE THREAD

**Issue by leofang** [NSLS-II/lightsource2-recipes#556]
In principle in one Conda recipe we can generate as many packages as we want, but our build script limited it to 1 package per recipe. This limitation is lifted by ~~PR #555~~ #559 , so @mrakitin suggested it's worth rebuilding those affected, including MPI-related stuff (@leofang) and matplotlib (@tacaswell).

**Comment by leofang** [comment]
Make sure #557 is merged before rebuilding!

**Comment by mrakitin** [comment]
I just realized we can now properly rebuild matplotlib. Will take a look tomorrow.

**Comment by leofang** [comment]
I suppose this issue can be closed since #585 is merged?

**Comment by mrakitin** [comment]
Yes.
