### ISSUE TITLE
Check a package exists on anaconda just before uploading

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#582]
As discussed in Slack with @leofang, we should check if the package exists in the Anaconda Cloud twice:
- first time when we [decide what to built](https://github.com/NSLS-II/lightsource2-recipes/blob/7402f5c82963d1b0d8328692e93632c6a81f03cc/scripts/build.py#L310)
- second time when the package is built just before the uploading [here](https://github.com/NSLS-II/lightsource2-recipes/blob/7402f5c82963d1b0d8328692e93632c6a81f03cc/scripts/build.py#L572).

We need it since the package might have been uploaded by the previous cron job.

The code should be extracted from the `decide_what_to_build(...)` function and reused in the two places.

**Comment by leofang** [comment]
I have a few stupid questions: How do the cron jobs work? Can't we build only one recipe per cron job? Or perhaps when the first cron job starts, we can leave a temp file in disk stating what packages it is handling, and ask the subsequent cron jobs to read that list to avoid collision? (Just trying to figure out how things work...)

**Comment by mrakitin** [comment]
It currently runs every 15 minutes on freyja, and checks the packages updated for the last 3 days (can be changed) here: https://github.com/NSLS-II/lightsource2-recipes/blob/02bf8a9943cca37eecc49dead0b46f578463a42e/scripts/nsls2-tag-build.sh#L21-L22

It's not ideal as every 15 minutes it runs a docker container to check if that package was built already, even if it was built before. We will improve it in the summer.

**Comment by mrakitin** [comment]
This may not be needed anymore as we are moving toward https://github.com/nsls-ii-forge. Reopen the issue if it's still needed.
