### ISSUE TITLE
dependencies on conda-forge

### ISSUE THREAD

**Issue by licode** [NSLS-II/lightsource2-recipes#67]
There are still some light dependencies from conda-forge. Keep this as a record.

- [x] attrs
- [x] boltons
- [x] humanize
- [x] historydict
- [x] ipyvolume
- [x] mongoquery
- [x] prettytable
- [x] pympler
- [x] readline
- [x] tifffile
- [x] traittypes

**Comment by licode** [comment]
let's still keep this as a record.

**Comment by mrakitin** [comment]
We currently don't use anything from conda-forge directly. Closing.
