### ISSUE TITLE
Package 'hunter' if it's useful for us

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#672]
- https://github.com/ionelmc/python-hunter
- https://pypi.org/project/hunter/

**Comment by ke-zhang-rd** [comment]
This will be tested first and won't be deployed 2019C3.0

**Comment by mrakitin** [comment]
@ke-zhang-rd, do you mind to take it over? If so, please follow the instructions at https://nsls-ii-forge.github.io/docs to generate a feedstock for the project.

**Comment by mrakitin** [comment]
It's implemented via https://github.com/nsls-ii-forge/hunter-feedstock/pull/1. The packages are available in https://anaconda.org/nsls2forge/hunter/files.
