### ISSUE TITLE
GIT_* variables in the version specification

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#736]
A recent update (#725) uses `GIT_DESCRIBE_TAG` and `GIT_DESCRIBE_NUMBER` to construct the version of the package:
https://github.com/NSLS-II/lightsource2-recipes/blob/9cc92be09ddcfb494efa5370dbf0267ded0e9b08/recipes-tag/lmfit-c/meta.yaml#L3

However, before the source archive is downloaded, we have no way to get these variables, and construct a valid version. This results in a negative check that the package exists, and the building system will try to rebuild it every time the job is run  (see the first part below), and it only knows about the name once it gets the source (see the second part below):
```
True     | linux-64/lmfit-c-.post-10.tar.bz2
INFO:build.py:True     | linux-64/lmfit-c-.post-10.tar.bz2
Build Order.
INFO:build.py:Build Order.
dependency_graph=<generator object resolve_dependencies at 0x7f3a9629f8b8>
linux-64/lmfit-c-.post-10.tar.bz2
INFO:build.py:linux-64/lmfit-c-.post-10.tar.bz2
Building: linux-64/lmfit-c-.post-10.tar.bz2
Cloning into bare repository '/home/builder/conda-bld/git_cache/github.com/NSLS-II/lmfit'...
Cloning into '/home/builder/conda-bld/work'...
done.
checkout: '5f540ec733489970d1a190e51be2ded9e413e61a'
Note: checking out '5f540ec733489970d1a190e51be2ded9e413e61a'.
...

INFO:conda_build.metadata:Attempting to finalize metadata for lmfit-c
Attempting to finalize metadata for lmfit-c
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['lmfit-c-8.2.2.post27-10.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
```

**Comment by mrakitin** [comment]
@stuwilkins, can we update it so that GIT vars are not used?

**Comment by leofang** [comment]
If the expected outcome is `['lmfit-c-8.2.2.post27-10.tar.bz2']`, perhaps you can just pin to a specific tag like https://github.com/NSLS-II/lmfit/releases/tag/v8.2.2?

**Comment by mrakitin** [comment]
Thanks @stuwilkins, your change resolved the issue in question.

Right now I am observing another problem with pinning `numpy x.x`, when the generated package name is `pycentroids-0.1.6-np114py37_0.tar.bz2`, but from the recipe it's parsed as `pycentroids-0.1.6-npxxpy37_0.tar.bz2'`. This causes a failure on checking already built packages.

I think we can solve it using conda-forge's approach, e.g. `{{ pin_compatible('numpy') }}` in the `run` section of the recipe, while keeping just `numpy` in the `build` section. See https://github.com/NSLS-II/lightsource2-recipes/pull/667/files for an example.

Any opinions on that?
