### ISSUE TITLE
clean up xpd related recipes

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/lightsource2-recipes#81]
attn @chiahaoliu @sbillinge @CJ-Wright

**Comment by danielballan** [comment]
@CJ-Wright Are you maintaining xpdacq/xpdan conda recipes somewhere? Are the ones in here up to date?

**Comment by CJ-Wright** [comment]
We don't have conda-recipes for the most recent release yet (I should get those out today or tomorrow). Currently XPD is running on a source install of our stack.

**Comment by danielballan** [comment]
Cool. When you do, would you push a copy here as a PR? To be clear, of course it's with me if you also maintain copies elsewhere. Having a copy here as well will keep our deployment process simple.

**Comment by CJ-Wright** [comment]
Of course.

**Comment by mrakitin** [comment]
Is there any progress on the issue?

**Comment by CJ-Wright** [comment]
I believe that some of the updates went in but if course we need more for this coming cycle, we haven't tagged the new versions though.

**Comment by mrakitin** [comment]
@CJ-Wright is managing the xpd* stack now, and the packages seem to be in a good shape. Closing.
