### ISSUE TITLE
Missing BMM deps

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/lightsource2-recipes#813]
Add pillow, openpyxl, lmfit.

**Comment by mrakitin** [comment]
Can it be migrated to https://github.com/nsls-ii-forge/project-management?

**Comment by danielballan** [comment]
Sure, can you transfer it?

**Comment by mrakitin** [comment]
Hmm, I don't have an option to transfer across organizations.

**Comment by danielballan** [comment]
Ah, I see. Will close and re-create there.

**Comment by mrakitin** [comment]
xref https://github.com/nsls-ii-forge/project-management/issues/5
