### ISSUE TITLE
Make a conda package for pyxs

### ISSUE THREAD

**Issue by arkilic** [NSLS-II/lightsource2-recipes#92]
Attn @licode 

https://github.com/NSLS-II-LIX/pyXS

PS: There is some swig in there, let's first check how difficult it is.

**Comment by licode** [comment]
OK, we can put this into the list. Let's find a time to stop by LIX and talk to them.

**Comment by danielballan** [comment]
FYI, I'm working with Lin on reworking this package.

**Comment by arkilic** [comment]
He mentioned. He asked if we can get him something like pyxrf that's why he wants to get in touch with Li

**Comment by licode** [comment]
Let's move on to beamline local software later
